Public Class Translate
    Shared Function ConvertToRomaji(ByVal fullstr As String)
        fullstr = fullstr.Replace("っき", "kき")
        fullstr = fullstr.Replace("っか", "kか")
        fullstr = fullstr.Replace("っく", "kく")
        fullstr = fullstr.Replace("っこ", "kこ")
        fullstr = fullstr.Replace("っけ", "kけ")

        fullstr = fullstr.Replace("っぎ", "gぎ")
        fullstr = fullstr.Replace("っが", "gが")
        fullstr = fullstr.Replace("っぐ", "gぐ")
        fullstr = fullstr.Replace("っご", "gご")
        fullstr = fullstr.Replace("っげ", "gげ")

        fullstr = fullstr.Replace("っし", "sし")
        fullstr = fullstr.Replace("っさ", "sさ")
        fullstr = fullstr.Replace("っす", "sす")
        fullstr = fullstr.Replace("っせ", "sせ")
        fullstr = fullstr.Replace("っそ", "sそ")

        fullstr = fullstr.Replace("っじ", "jじ")
        fullstr = fullstr.Replace("っざ", "zざ")
        fullstr = fullstr.Replace("っず", "zず")
        fullstr = fullstr.Replace("っぜ", "zぜ")
        fullstr = fullstr.Replace("っぞ", "zぞ")

        fullstr = fullstr.Replace("っぴ", "pぴ")
        fullstr = fullstr.Replace("っぱ", "pぱ")
        fullstr = fullstr.Replace("っぷ", "pぷ")
        fullstr = fullstr.Replace("っぽ", "pぺ")
        fullstr = fullstr.Replace("っぺ", "pぽ")

        fullstr = fullstr.Replace("っち", "tち")
        fullstr = fullstr.Replace("った", "tた")
        fullstr = fullstr.Replace("っつ", "tつ")
        fullstr = fullstr.Replace("っと", "tと")
        fullstr = fullstr.Replace("って", "tて")

        fullstr = fullstr.Replace("きゃ", "kya")
        fullstr = fullstr.Replace("きゅ", "kyu")
        fullstr = fullstr.Replace("きょ", "kyo")
        fullstr = fullstr.Replace("しゃ", "sha")
        fullstr = fullstr.Replace("しゅ", "shu")
        fullstr = fullstr.Replace("しょ", "sho")
        fullstr = fullstr.Replace("ちゃ", "cha")
        fullstr = fullstr.Replace("ちゅ", "chu")
        fullstr = fullstr.Replace("ちょ", "cho")
        fullstr = fullstr.Replace("にゃ", "nya")
        fullstr = fullstr.Replace("にゅ", "nyu")
        fullstr = fullstr.Replace("にょ", "nyo")
        fullstr = fullstr.Replace("ひゃ", "hya")
        fullstr = fullstr.Replace("ひゅ", "gyu")
        fullstr = fullstr.Replace("ひょ", "hyo")
        fullstr = fullstr.Replace("みゃ", "mya")
        fullstr = fullstr.Replace("みゅ", "myu")
        fullstr = fullstr.Replace("みょ", "myo")
        fullstr = fullstr.Replace("りゃ", "rya")
        fullstr = fullstr.Replace("りゅ", "ryu")
        fullstr = fullstr.Replace("りょ", "ryo")
        fullstr = fullstr.Replace("ぎゃ", "gya")
        fullstr = fullstr.Replace("ぎゅ", "gyu")
        fullstr = fullstr.Replace("ぎょ", "gyo")
        fullstr = fullstr.Replace("じゃ", "ja")
        fullstr = fullstr.Replace("じゅ", "ju")
        fullstr = fullstr.Replace("じょ", "jo")
        fullstr = fullstr.Replace("びゃ", "bya")
        fullstr = fullstr.Replace("びゅ", "byu")
        fullstr = fullstr.Replace("びょ", "byo")
        fullstr = fullstr.Replace("ぴゃ", "pya")
        fullstr = fullstr.Replace("ぴゅ", "pyu")
        fullstr = fullstr.Replace("ぴょ", "pyo")

        fullstr = fullstr.Replace("か", "ka")
        fullstr = fullstr.Replace("き", "ki")
        fullstr = fullstr.Replace("く", "ku")
        fullstr = fullstr.Replace("け", "ke")
        fullstr = fullstr.Replace("こ", "ko")
        fullstr = fullstr.Replace("さ", "sa")
        fullstr = fullstr.Replace("し", "shi")
        fullstr = fullstr.Replace("す", "su")
        fullstr = fullstr.Replace("せ", "se")
        fullstr = fullstr.Replace("そ", "so")
        fullstr = fullstr.Replace("た", "ta")
        fullstr = fullstr.Replace("ち", "chi")
        fullstr = fullstr.Replace("つ", "tsu")
        fullstr = fullstr.Replace("て", "te")
        fullstr = fullstr.Replace("と", "to")
        fullstr = fullstr.Replace("な", "na")
        fullstr = fullstr.Replace("に", "ni")
        fullstr = fullstr.Replace("ぬ", "nu")
        fullstr = fullstr.Replace("ね", "ne")
        fullstr = fullstr.Replace("の", "no")
        fullstr = fullstr.Replace("は", "ha")
        fullstr = fullstr.Replace("ひ", "hi")
        fullstr = fullstr.Replace("ふ", "fu")
        fullstr = fullstr.Replace("へ", "he")
        fullstr = fullstr.Replace("ほ", "ho")
        fullstr = fullstr.Replace("ま", "ma")
        fullstr = fullstr.Replace("み", "mi")
        fullstr = fullstr.Replace("む", "mu")
        fullstr = fullstr.Replace("め", "me")
        fullstr = fullstr.Replace("も", "mo")
        fullstr = fullstr.Replace("や", "ya")
        fullstr = fullstr.Replace("ゆ", "yu")
        fullstr = fullstr.Replace("よ", "yo")
        fullstr = fullstr.Replace("ら", "ra")
        fullstr = fullstr.Replace("り", "ri")
        fullstr = fullstr.Replace("る", "ru")
        fullstr = fullstr.Replace("れ", "re")
        fullstr = fullstr.Replace("ろ", "ro")
        fullstr = fullstr.Replace("わ", "wa")
        fullstr = fullstr.Replace("を", "wo")

        fullstr = fullstr.Replace("が", "ga")
        fullstr = fullstr.Replace("ぎ", "gi")
        fullstr = fullstr.Replace("ぐ", "gu")
        fullstr = fullstr.Replace("げ", "ge")
        fullstr = fullstr.Replace("ご", "go")
        fullstr = fullstr.Replace("ざ", "za")
        fullstr = fullstr.Replace("じ", "ji")
        fullstr = fullstr.Replace("ず", "zu")
        fullstr = fullstr.Replace("ぜ", "ze")
        fullstr = fullstr.Replace("ぞ", "zo")
        fullstr = fullstr.Replace("だ", "da")
        fullstr = fullstr.Replace("づ", "du")
        fullstr = fullstr.Replace("で", "de")
        fullstr = fullstr.Replace("ど", "do")
        fullstr = fullstr.Replace("ば", "ba")
        fullstr = fullstr.Replace("び", "bi")
        fullstr = fullstr.Replace("ぶ", "bu")
        fullstr = fullstr.Replace("べ", "be")
        fullstr = fullstr.Replace("ぼ", "bo")
        fullstr = fullstr.Replace("ぱ", "pa")
        fullstr = fullstr.Replace("ぴ", "pi")
        fullstr = fullstr.Replace("ぷ", "pu")
        fullstr = fullstr.Replace("ぺ", "pe")
        fullstr = fullstr.Replace("ぽ", "po")

        fullstr = fullstr.Replace("あ", "a")
        fullstr = fullstr.Replace("え", "e")
        fullstr = fullstr.Replace("い", "i")
        fullstr = fullstr.Replace("お", "o")
        fullstr = fullstr.Replace("う", "u")
        fullstr = fullstr.Replace("ん", "n")
        Return fullstr
    End Function
End Class
